name: Build and Trigger QA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: âœ… Checkout Dev Repo
      uses: actions/checkout@v4

    - name: ğŸ”¹ Compile HelloWord.java
      run: |
        dir
        javac HelloWord.java
      shell: cmd

    - name: ğŸš€ Run HelloWord
      run: |
        java HelloWord
      shell: cmd

    - name: ğŸ” Trigger QA Workflow via repository_dispatch
      run: |
        curl -X POST https://github.com/akbarmaulino/Selenium-MineProject/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.QA_PAT }}" \
          -d '{"event_type":"run-qa"}'
      shell: bash

